import '../models/barber.dart';
import '../models/barbershop.dart';
import '../models/booking.dart';
import '../models/reel.dart';
import '../models/review.dart';
import '../models/service.dart';
import '../theme/hallaq_images.dart';

class DemoContent {
  static final _shopsAll = <Barbershop>[
    Barbershop(
      id: 'demo_shop_01',
      ownerProfileId: 'demo_profile_shop_01',
      name: 'Manama Barbershop',
      description: 'Premium grooming in the heart of Manama. Clean fades, sharp beard work, luxury finish.',
      coverUrl: HallaqImages.shopCover(variant: '01'),
      logoUrl: HallaqImages.goldScissorsIllustration(variant: '01'),
      area: 'Manama',
      address: 'Block 338, Road 3801, Manama, Bahrain',
      lat: 26.2235,
      lng: 50.5876,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2235,50.5876',
      phone: '17001234',
      whatsapp: '+973 3900 1234',
      instagram: '@manama_barbershop',
      openingHours: {
        'sat': '10:00-23:00',
        'sun': '10:00-23:00',
        'mon': '12:00-23:00',
        'tue': '12:00-23:00',
        'wed': '12:00-23:00',
        'thu': '12:00-00:00',
        'fri': '14:00-00:00',
      },
      isFeatured: true,
      ratingAvg: 4.9,
      ratingCount: 268,
      badgeVerified: true,
      badgeElite: true,
      badgeTopRated: true,
      badgeCertified: true,
    ),
    Barbershop(
      id: 'demo_shop_02',
      ownerProfileId: 'demo_profile_shop_02',
      name: 'Seef Cuts Lounge',
      description: 'Luxury lounge vibe in Seef. Modern textures, tapers, and premium packages.',
      coverUrl: HallaqImages.shopCover(variant: '02'),
      logoUrl: HallaqImages.goldBarberPoleIllustration(variant: '01'),
      area: 'Seef',
      address: 'Seef District, Road 2819, Bahrain',
      lat: 26.2389,
      lng: 50.5340,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2389,50.5340',
      phone: '17004567',
      whatsapp: '+973 3900 4567',
      instagram: '@seef_cuts_lounge',
      openingHours: {
        'sat': '10:00-22:30',
        'sun': '10:00-22:30',
        'mon': '10:00-22:30',
        'tue': '10:00-22:30',
        'wed': '10:00-22:30',
        'thu': '10:00-23:30',
        'fri': '13:30-23:30',
      },
      isFeatured: true,
      ratingAvg: 4.8,
      ratingCount: 194,
      badgeVerified: true,
      badgeTrending: true,
    ),
    Barbershop(
      id: 'demo_shop_03',
      ownerProfileId: 'demo_profile_shop_03',
      name: 'Riffa Grooming House',
      description: 'Precision cuts and classic service. Known for clean blends and consistent results.',
      coverUrl: HallaqImages.shopCover(variant: '03'),
      logoUrl: HallaqImages.goldScissorsIllustration(variant: '02'),
      area: 'Riffa',
      address: 'East Riffa, Road 1234, Bahrain',
      lat: 26.1302,
      lng: 50.5550,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.1302,50.5550',
      phone: '17007890',
      whatsapp: '+973 3900 7890',
      instagram: '@riffa_grooming_house',
      openingHours: {
        'sat': '10:00-22:00',
        'sun': '10:00-22:00',
        'mon': '10:00-22:00',
        'tue': '10:00-22:00',
        'wed': '10:00-22:00',
        'thu': '10:00-23:00',
        'fri': '14:00-23:00',
      },
      ratingAvg: 4.7,
      ratingCount: 121,
      badgeVerified: true,
      badgeCertified: true,
    ),
    Barbershop(
      id: 'demo_shop_04',
      ownerProfileId: 'demo_profile_shop_04',
      name: 'Juffair Fade Studio',
      description: 'Fade-first studio with sharp details. Modern finishes and beard sculpting.',
      coverUrl: HallaqImages.shopCover(variant: '04'),
      logoUrl: HallaqImages.goldBarberPoleIllustration(variant: '02'),
      area: 'Juffair',
      address: 'Juffair, Road 4020, Bahrain',
      lat: 26.2172,
      lng: 50.6031,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2172,50.6031',
      phone: '17003210',
      whatsapp: '+973 3900 3210',
      instagram: '@juffair_fade_studio',
      openingHours: {
        'sat': '11:00-23:00',
        'sun': '11:00-23:00',
        'mon': '11:00-23:00',
        'tue': '11:00-23:00',
        'wed': '11:00-23:00',
        'thu': '11:00-00:00',
        'fri': '14:00-00:00',
      },
      ratingAvg: 4.6,
      ratingCount: 88,
      badgeTrending: true,
    ),
    Barbershop(
      id: 'demo_shop_05',
      ownerProfileId: 'demo_profile_shop_05',
      name: 'Muharraq Classic Barber',
      description: 'Classic Bahrain barbering with a luxury upgrade. Hot towel shave and clean lines.',
      coverUrl: HallaqImages.shopCover(variant: '05'),
      logoUrl: HallaqImages.goldScissorsIllustration(variant: '03'),
      area: 'Muharraq',
      address: 'Muharraq, Road 711, Bahrain',
      lat: 26.2570,
      lng: 50.6115,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2570,50.6115',
      phone: '17005432',
      whatsapp: '+973 3900 5432',
      instagram: '@muharraq_classic',
      openingHours: {
        'sat': '09:30-22:00',
        'sun': '09:30-22:00',
        'mon': '09:30-22:00',
        'tue': '09:30-22:00',
        'wed': '09:30-22:00',
        'thu': '09:30-23:00',
        'fri': '13:30-23:00',
      },
      ratingAvg: 4.8,
      ratingCount: 156,
      badgeVerified: true,
      badgeTopRated: true,
    ),
    Barbershop(
      id: 'demo_shop_06',
      ownerProfileId: 'demo_profile_shop_06',
      name: 'Saar Gentlemen Club',
      description: 'Premium gentleman grooming. Clean ambience, premium products, strong finishing.',
      coverUrl: HallaqImages.shopCover(variant: '06'),
      logoUrl: HallaqImages.goldBarberPoleIllustration(variant: '03'),
      area: 'Saar',
      address: 'Saar, Road 505, Bahrain',
      lat: 26.2011,
      lng: 50.4993,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2011,50.4993',
      phone: '17006789',
      whatsapp: '+973 3900 6789',
      instagram: '@saar_gentlemen_club',
      openingHours: {
        'sat': '10:00-22:30',
        'sun': '10:00-22:30',
        'mon': '10:00-22:30',
        'tue': '10:00-22:30',
        'wed': '10:00-22:30',
        'thu': '10:00-23:30',
        'fri': '14:00-23:30',
      },
      ratingAvg: 4.7,
      ratingCount: 94,
      badgeCertified: true,
    ),
    Barbershop(
      id: 'demo_shop_07',
      ownerProfileId: 'demo_profile_shop_07',
      name: 'Budaiya Heritage Barber',
      description: 'Classic service and modern detail. Known for clean beard shaping and smooth blends.',
      coverUrl: HallaqImages.shopCover(variant: '07'),
      logoUrl: HallaqImages.goldScissorsIllustration(variant: '04'),
      area: 'Budaiya',
      address: 'Budaiya Highway, Bahrain',
      lat: 26.2230,
      lng: 50.4657,
      googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2230,50.4657',
      phone: '17009876',
      whatsapp: '+973 3900 9876',
      instagram: '@budaiya_heritage_barber',
      openingHours: {
        'sat': '10:00-22:00',
        'sun': '10:00-22:00',
        'mon': '10:00-22:00',
        'tue': '10:00-22:00',
        'wed': '10:00-22:00',
        'thu': '10:00-23:00',
        'fri': '14:00-23:00',
      },
      ratingAvg: 4.5,
      ratingCount: 71,
    ),
    Barbershop(
      id: 'demo_shop_08',
      ownerProfileId: 'demo_profile_shop_08',
      name: 'Isa Town Precision',
      description: 'Precision fades and premium grooming packages. Fast, clean, consistent.',
      coverUrl: HallaqImages.shopCover(variant: '08'),
      logoUrl: HallaqImages.goldBarberPoleIllustration(variant: '04'),
      area: 'Isa Town',
      address: 'Isa Town, Road 130, Bahrain',
      lat: 26.1674,
      lng: 50.5480,
      phone: '17001122',
      whatsapp: '+973 3900 1122',
      instagram: '@isatown_precision',
      openingHours: {
        'sat': '10:00-22:30',
        'sun': '10:00-22:30',
        'mon': '10:00-22:30',
        'tue': '10:00-22:30',
        'wed': '10:00-22:30',
        'thu': '10:00-23:30',
        'fri': '14:00-23:30',
      },
      ratingAvg: 4.6,
      ratingCount: 83,
    ),
    Barbershop(
      id: 'demo_shop_09',
      ownerProfileId: 'demo_profile_shop_09',
      name: 'Hidd Dockside Grooming',
      description: 'Modern barbering near the sea. Clean lines, sharp beard trims, premium service.',
      coverUrl: HallaqImages.shopCover(variant: '09'),
      logoUrl: HallaqImages.goldScissorsIllustration(variant: '05'),
      area: 'Hidd',
      address: 'Hidd, Road 230, Bahrain',
      lat: 26.2436,
      lng: 50.6527,
      phone: '17003344',
      whatsapp: '+973 3900 3344',
      instagram: '@hidd_dockside_grooming',
      openingHours: {
        'sat': '10:30-22:30',
        'sun': '10:30-22:30',
        'mon': '10:30-22:30',
        'tue': '10:30-22:30',
        'wed': '10:30-22:30',
        'thu': '10:30-23:30',
        'fri': '14:00-23:30',
      },
      ratingAvg: 4.4,
      ratingCount: 59,
    ),
    Barbershop(
      id: 'demo_shop_10',
      ownerProfileId: 'demo_profile_shop_10',
      name: 'Hamala Gold Lounge',
      description: 'Black-and-gold lounge feel with premium finishes. Perfect for events and business looks.',
      coverUrl: HallaqImages.shopCover(variant: '10'),
      logoUrl: HallaqImages.goldBarberPoleIllustration(variant: '05'),
      area: 'Hamala',
      address: 'Hamala, Road 1201, Bahrain',
      lat: 26.1579,
      lng: 50.4623,
      phone: '17005566',
      whatsapp: '+973 3900 5566',
      instagram: '@hamala_gold_lounge',
      openingHours: {
        'sat': '10:00-23:00',
        'sun': '10:00-23:00',
        'mon': '10:00-23:00',
        'tue': '10:00-23:00',
        'wed': '10:00-23:00',
        'thu': '10:00-00:00',
        'fri': '14:00-00:00',
      },
      isFeatured: true,
      ratingAvg: 4.8,
      ratingCount: 132,
      badgeVerified: true,
    ),
  ];

  static final shops = _shopsAll.take(4).toList(growable: false);

  static final _barbersAll = <Barber>[
    Barber(
      id: 'demo_barber_01',
      profileId: 'demo_profile_barber_01',
      slug: 'ahmed-al-doseri',
      displayName: 'Ahmed Al Doseri',
      avatarUrl: HallaqImages.barberAvatar(variant: '01'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '01'),
      bio: 'Precision fades, beard sculpting, and premium finish.',
      specialty: 'Skin Fade • Beard Sculpt',
      shopId: 'demo_shop_01',
      area: 'Manama',
      address: 'Block 338, Manama',
      ratingAvg: 4.9,
      ratingCount: 124,
      followersCount: 9820,
      reviewsCount: 124,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 15,
      queueLength: 3,
      badgeVerified: true,
      badgeElite: true,
      badgeTrending: true,
      badgeTopRated: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_02',
      profileId: 'demo_profile_barber_02',
      slug: 'hassan-al-noor',
      displayName: 'Hassan Al Noor',
      avatarUrl: HallaqImages.barberAvatar(variant: '02'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '02'),
      bio: 'Clean blends and modern textures with a luxury feel.',
      specialty: 'Low Taper • Texture',
      shopId: 'demo_shop_01',
      area: 'Manama',
      address: 'Block 338, Manama',
      ratingAvg: 4.8,
      ratingCount: 97,
      followersCount: 6310,
      reviewsCount: 97,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
      badgeTopRated: true,
    ),
    Barber(
      id: 'demo_barber_03',
      profileId: 'demo_profile_barber_03',
      slug: 'faisal-al-sayed',
      displayName: 'Faisal Al Sayed',
      avatarUrl: HallaqImages.barberAvatar(variant: '03'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '03'),
      bio: 'Luxury classic cuts and hot towel shave.',
      specialty: 'Classic Cut • Hot Towel Shave',
      shopId: 'demo_shop_01',
      area: 'Manama',
      address: 'Block 338, Manama',
      ratingAvg: 4.7,
      ratingCount: 76,
      followersCount: 4020,
      reviewsCount: 76,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 25,
      queueLength: 5,
      badgeVerified: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_04',
      profileId: 'demo_profile_barber_04',
      slug: 'mohammed-ali',
      displayName: 'Mohammed Ali',
      avatarUrl: HallaqImages.barberAvatar(variant: '04'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '04'),
      bio: 'Modern cuts with clean lines and strong finishing.',
      specialty: 'Mid Fade • Line Up',
      shopId: 'demo_shop_02',
      area: 'Seef',
      address: 'Seef District',
      ratingAvg: 4.9,
      ratingCount: 141,
      followersCount: 11240,
      reviewsCount: 141,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 10,
      queueLength: 2,
      badgeVerified: true,
      badgeElite: true,
      badgeTrending: true,
      badgeTopRated: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_05',
      profileId: 'demo_profile_barber_05',
      slug: 'ali-hassan',
      displayName: 'Ali Hassan',
      avatarUrl: HallaqImages.barberAvatar(variant: '05'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '05'),
      bio: 'Fast, clean, and consistent. Premium beard blends.',
      specialty: 'Beard Blend • Taper',
      shopId: 'demo_shop_02',
      area: 'Seef',
      address: 'Seef District',
      ratingAvg: 4.6,
      ratingCount: 63,
      followersCount: 2980,
      reviewsCount: 63,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_06',
      profileId: 'demo_profile_barber_06',
      slug: 'yousef-al-haddad',
      displayName: 'Yousef Al Haddad',
      avatarUrl: HallaqImages.barberAvatar(variant: '06'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '06'),
      bio: 'Premium event looks and sharp fades.',
      specialty: 'Event Grooming • Fade',
      shopId: 'demo_shop_02',
      area: 'Seef',
      address: 'Seef District',
      ratingAvg: 4.7,
      ratingCount: 58,
      followersCount: 3650,
      reviewsCount: 58,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 30,
      queueLength: 4,
      badgeVerified: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_07',
      profileId: 'demo_profile_barber_07',
      slug: 'salman-al-noor',
      displayName: 'Salman Al Noor',
      avatarUrl: HallaqImages.barberAvatar(variant: '07'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '07'),
      bio: 'Modern textured crops and crisp line-ups.',
      specialty: 'Texture Crop • Burst Fade',
      shopId: 'demo_shop_03',
      area: 'Riffa',
      address: 'East Riffa',
      ratingAvg: 4.8,
      ratingCount: 88,
      followersCount: 5120,
      reviewsCount: 88,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 18,
      queueLength: 3,
      badgeVerified: true,
      badgeTrending: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_08',
      profileId: 'demo_profile_barber_08',
      slug: 'abdullah-al-jassim',
      displayName: 'Abdullah Al Jassim',
      avatarUrl: HallaqImages.barberAvatar(variant: '08'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '08'),
      bio: 'Classic cuts with premium finish and clean beard work.',
      specialty: 'Classic Cut • Beard Trim',
      shopId: 'demo_shop_03',
      area: 'Riffa',
      address: 'East Riffa',
      ratingAvg: 4.6,
      ratingCount: 52,
      followersCount: 2410,
      reviewsCount: 52,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_09',
      profileId: 'demo_profile_barber_09',
      slug: 'majed-al-ansari',
      displayName: 'Majed Al Ansari',
      avatarUrl: HallaqImages.barberAvatar(variant: '09'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '09'),
      bio: 'Sharp fades and clean finishing touches.',
      specialty: 'High Fade • Line Up',
      shopId: 'demo_shop_03',
      area: 'Riffa',
      address: 'East Riffa',
      ratingAvg: 4.7,
      ratingCount: 61,
      followersCount: 3300,
      reviewsCount: 61,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 22,
      queueLength: 4,
      badgeVerified: true,
      badgeTopRated: true,
    ),
    Barber(
      id: 'demo_barber_10',
      profileId: 'demo_profile_barber_10',
      slug: 'omar-al-banna',
      displayName: 'Omar Al Banna',
      avatarUrl: HallaqImages.barberAvatar(variant: '10'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '10'),
      bio: 'Fade studio specialist with premium beard sculpt.',
      specialty: 'Fade Specialist • Beard Sculpt',
      shopId: 'demo_shop_04',
      area: 'Juffair',
      address: 'Juffair',
      ratingAvg: 4.7,
      ratingCount: 73,
      followersCount: 4980,
      reviewsCount: 73,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 12,
      queueLength: 2,
      badgeTrending: true,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_11',
      profileId: 'demo_profile_barber_11',
      slug: 'rashid-al-humaidan',
      displayName: 'Rashid Al Humaidan',
      avatarUrl: HallaqImages.barberAvatar(variant: '11'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '11'),
      bio: 'Modern tapers and clean trims with luxury finish.',
      specialty: 'Taper • Beard Trim',
      shopId: 'demo_shop_04',
      area: 'Juffair',
      address: 'Juffair',
      ratingAvg: 4.5,
      ratingCount: 44,
      followersCount: 1890,
      reviewsCount: 44,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_12',
      profileId: 'demo_profile_barber_12',
      slug: 'saud-al-dhahrani',
      displayName: 'Saud Al Dhahrani',
      avatarUrl: HallaqImages.barberAvatar(variant: '12'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '12'),
      bio: 'Beard styling and classic service.',
      specialty: 'Beard Styling • Classic Cut',
      shopId: 'demo_shop_05',
      area: 'Muharraq',
      address: 'Muharraq',
      ratingAvg: 4.8,
      ratingCount: 110,
      followersCount: 7740,
      reviewsCount: 110,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 16,
      queueLength: 3,
      badgeVerified: true,
      badgeTopRated: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_13',
      profileId: 'demo_profile_barber_13',
      slug: 'khalid-al-jasmi',
      displayName: 'Khalid Al Jasmi',
      avatarUrl: HallaqImages.barberAvatar(variant: '13'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '13'),
      bio: 'Premium classic cuts with crisp edges.',
      specialty: 'Classic Cut • Line Up',
      shopId: 'demo_shop_05',
      area: 'Muharraq',
      address: 'Muharraq',
      ratingAvg: 4.6,
      ratingCount: 65,
      followersCount: 3050,
      reviewsCount: 65,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_14',
      profileId: 'demo_profile_barber_14',
      slug: 'nasser-al-mousa',
      displayName: 'Nasser Al Mousa',
      avatarUrl: HallaqImages.barberAvatar(variant: '14'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '14'),
      bio: 'Gentleman club style grooming and premium packages.',
      specialty: 'Luxury Grooming • Beard Blend',
      shopId: 'demo_shop_06',
      area: 'Saar',
      address: 'Saar',
      ratingAvg: 4.7,
      ratingCount: 58,
      followersCount: 3620,
      reviewsCount: 58,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 20,
      queueLength: 4,
      badgeCertified: true,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_15',
      profileId: 'demo_profile_barber_15',
      slug: 'mohamed-al-qarni',
      displayName: 'Mohamed Al Qarni',
      avatarUrl: HallaqImages.barberAvatar(variant: '15'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '15'),
      bio: 'Beard sculpting and clean modern tapers.',
      specialty: 'Beard Sculpt • Taper',
      shopId: 'demo_shop_06',
      area: 'Saar',
      address: 'Saar',
      ratingAvg: 4.5,
      ratingCount: 39,
      followersCount: 1550,
      reviewsCount: 39,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
    ),
    Barber(
      id: 'demo_barber_16',
      profileId: 'demo_profile_barber_16',
      slug: 'abdulrahman-al-mazrouei',
      displayName: 'Abdulrahman Al Mazrouei',
      avatarUrl: HallaqImages.barberAvatar(variant: '16'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '16'),
      bio: 'Classic and modern styles with premium finishing.',
      specialty: 'Classic Cut • Fade',
      shopId: 'demo_shop_07',
      area: 'Budaiya',
      address: 'Budaiya',
      ratingAvg: 4.6,
      ratingCount: 47,
      followersCount: 2120,
      reviewsCount: 47,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 14,
      queueLength: 2,
    ),
    Barber(
      id: 'demo_barber_17',
      profileId: 'demo_profile_barber_17',
      slug: 'sultan-al-zayani',
      displayName: 'Sultan Al Zayani',
      avatarUrl: HallaqImages.barberAvatar(variant: '17'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '17'),
      bio: 'Precision fades and premium beard work.',
      specialty: 'Fade • Beard Trim',
      shopId: 'demo_shop_08',
      area: 'Isa Town',
      address: 'Isa Town',
      ratingAvg: 4.5,
      ratingCount: 42,
      followersCount: 1800,
      reviewsCount: 42,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 19,
      queueLength: 3,
    ),
    Barber(
      id: 'demo_barber_18',
      profileId: 'demo_profile_barber_18',
      slug: 'bader-al-khater',
      displayName: 'Bader Al Khater',
      avatarUrl: HallaqImages.barberAvatar(variant: '18'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '18'),
      bio: 'Dockside vibe with clean cuts and sharp finishing.',
      specialty: 'Taper • Line Up',
      shopId: 'demo_shop_09',
      area: 'Hidd',
      address: 'Hidd',
      ratingAvg: 4.4,
      ratingCount: 38,
      followersCount: 1290,
      reviewsCount: 38,
      isIndependent: false,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
    ),
    Barber(
      id: 'demo_barber_19',
      profileId: 'demo_profile_barber_19',
      slug: 'tariq-al-mansoori',
      displayName: 'Tariq Al Mansoori',
      avatarUrl: HallaqImages.barberAvatar(variant: '19'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '19'),
      bio: 'Premium event grooming and sharp fades.',
      specialty: 'Event Grooming • Fade',
      shopId: 'demo_shop_10',
      area: 'Hamala',
      address: 'Hamala',
      ratingAvg: 4.8,
      ratingCount: 91,
      followersCount: 6100,
      reviewsCount: 91,
      isIndependent: false,
      availableNow: true,
      waitingTimeMin: 16,
      queueLength: 3,
      badgeVerified: true,
      badgeTrending: true,
    ),
    Barber(
      id: 'demo_barber_20',
      profileId: 'demo_profile_barber_20',
      slug: 'hassan-noor',
      displayName: 'Hassan Noor',
      avatarUrl: HallaqImages.barberAvatar(variant: '20'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '20'),
      bio: 'Independent premium grooming. Book for home or hotel visits.',
      specialty: 'Fade • Beard Sculpt',
      shopId: null,
      area: 'Juffair',
      address: 'Juffair',
      ratingAvg: 4.9,
      ratingCount: 144,
      followersCount: 15620,
      reviewsCount: 144,
      isIndependent: true,
      availableNow: true,
      waitingTimeMin: 35,
      queueLength: 0,
      badgeVerified: true,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_21',
      profileId: 'demo_profile_barber_21',
      slug: 'yassin-al-hindi',
      displayName: 'Yassin Al Hindi',
      avatarUrl: HallaqImages.barberAvatar(variant: '21'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '21'),
      bio: 'Independent luxury cuts with a clean, modern finish.',
      specialty: 'Low Taper • Texture',
      shopId: null,
      area: 'Seef',
      address: 'Seef',
      ratingAvg: 4.7,
      ratingCount: 81,
      followersCount: 6240,
      reviewsCount: 81,
      isIndependent: true,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_22',
      profileId: 'demo_profile_barber_22',
      slug: 'ibrahim-al-dossary',
      displayName: 'Ibrahim Al Dossary',
      avatarUrl: HallaqImages.barberAvatar(variant: '22'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '22'),
      bio: 'Independent barber focused on classic cuts and premium beard trims.',
      specialty: 'Classic Cut • Beard Trim',
      shopId: null,
      area: 'Muharraq',
      address: 'Muharraq',
      ratingAvg: 4.6,
      ratingCount: 64,
      followersCount: 3180,
      reviewsCount: 64,
      isIndependent: true,
      availableNow: true,
      waitingTimeMin: 45,
      queueLength: 0,
    ),
    Barber(
      id: 'demo_barber_23',
      profileId: 'demo_profile_barber_23',
      slug: 'saif-al-bahraini',
      displayName: 'Saif Al Bahraini',
      avatarUrl: HallaqImages.barberAvatar(variant: '23'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '23'),
      bio: 'Independent, high-detail fades and clean lines.',
      specialty: 'Skin Fade • Line Up',
      shopId: null,
      area: 'Riffa',
      address: 'Riffa',
      ratingAvg: 4.8,
      ratingCount: 92,
      followersCount: 7840,
      reviewsCount: 92,
      isIndependent: true,
      availableNow: true,
      waitingTimeMin: 25,
      queueLength: 0,
      badgeCertified: true,
    ),
    Barber(
      id: 'demo_barber_24',
      profileId: 'demo_profile_barber_24',
      slug: 'musa-al-sheikh',
      displayName: 'Musa Al Sheikh',
      avatarUrl: HallaqImages.barberAvatar(variant: '24'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '24'),
      bio: 'Independent luxury grooming, ideal for business looks.',
      specialty: 'Executive Cut • Beard Sculpt',
      shopId: null,
      area: 'Saar',
      address: 'Saar',
      ratingAvg: 4.7,
      ratingCount: 55,
      followersCount: 4020,
      reviewsCount: 55,
      isIndependent: true,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
    Barber(
      id: 'demo_barber_25',
      profileId: 'demo_profile_barber_25',
      slug: 'zain-al-haddad',
      displayName: 'Zain Al Haddad',
      avatarUrl: HallaqImages.barberAvatar(variant: '25'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '25'),
      bio: 'Independent barber with premium event packages and clean fades.',
      specialty: 'Event Grooming • Fade',
      shopId: null,
      area: 'Manama',
      address: 'Manama',
      ratingAvg: 4.6,
      ratingCount: 49,
      followersCount: 3010,
      reviewsCount: 49,
      isIndependent: true,
      availableNow: true,
      waitingTimeMin: 30,
      queueLength: 0,
    ),
    Barber(
      id: 'demo_barber_26',
      profileId: 'demo_profile_barber_26',
      slug: 'nawaf-al-juffairi',
      displayName: 'Nawaf Al Juffairi',
      avatarUrl: HallaqImages.barberAvatar(variant: '26'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '26'),
      bio: 'Independent fade specialist with clean modern finish.',
      specialty: 'Fade • Texture',
      shopId: null,
      area: 'Juffair',
      address: 'Juffair',
      ratingAvg: 4.5,
      ratingCount: 37,
      followersCount: 1950,
      reviewsCount: 37,
      isIndependent: true,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
    ),
    Barber(
      id: 'demo_barber_27',
      profileId: 'demo_profile_barber_27',
      slug: 'abdulaziz-al-seefi',
      displayName: 'Abdulaziz Al Seefi',
      avatarUrl: HallaqImages.barberAvatar(variant: '27'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '27'),
      bio: 'Independent barber focused on premium beard work and line ups.',
      specialty: 'Beard Trim • Line Up',
      shopId: null,
      area: 'Seef',
      address: 'Seef',
      ratingAvg: 4.7,
      ratingCount: 66,
      followersCount: 4870,
      reviewsCount: 66,
      isIndependent: true,
      availableNow: true,
      waitingTimeMin: 40,
      queueLength: 0,
    ),
    Barber(
      id: 'demo_barber_28',
      profileId: 'demo_profile_barber_28',
      slug: 'faris-al-muharraqi',
      displayName: 'Faris Al Muharraqi',
      avatarUrl: HallaqImages.barberAvatar(variant: '28'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '28'),
      bio: 'Independent classic cuts with luxury service.',
      specialty: 'Classic Cut • Hot Towel Shave',
      shopId: null,
      area: 'Muharraq',
      address: 'Muharraq',
      ratingAvg: 4.6,
      ratingCount: 53,
      followersCount: 3320,
      reviewsCount: 53,
      isIndependent: true,
      availableNow: true,
      waitingTimeMin: 50,
      queueLength: 0,
    ),
    Barber(
      id: 'demo_barber_29',
      profileId: 'demo_profile_barber_29',
      slug: 'saleh-al-riffai',
      displayName: 'Saleh Al Riffai',
      avatarUrl: HallaqImages.barberAvatar(variant: '29'),
      coverUrl: HallaqImages.professionalBarberPortrait(variant: '29'),
      bio: 'Independent premium grooming for clean business looks.',
      specialty: 'Executive Cut • Beard Sculpt',
      shopId: null,
      area: 'Riffa',
      address: 'Riffa',
      ratingAvg: 4.8,
      ratingCount: 74,
      followersCount: 6050,
      reviewsCount: 74,
      isIndependent: true,
      availableNow: false,
      waitingTimeMin: null,
      queueLength: null,
      badgeVerified: true,
    ),
  ];

  static const _demoBarberIds = <String>{
    'demo_barber_01',
    'demo_barber_02',
    'demo_barber_04',
    'demo_barber_05',
    'demo_barber_07',
    'demo_barber_08',
    'demo_barber_10',
    'demo_barber_11',
  };

  static final barbers = _barbersAll.where((b) => _demoBarberIds.contains(b.id)).toList(growable: false);

  static final services = <Service>[
    Service(
      id: 'demo_service_01',
      shopId: 'demo_shop_01',
      barberId: null,
      nameEn: 'Haircut',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 6.0,
      durationMinutes: 40,
      imageUrl: null,
      category: 'Demo',
      isPopular: true,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_02',
      shopId: 'demo_shop_01',
      barberId: null,
      nameEn: 'Haircut + Beard',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 9.0,
      durationMinutes: 60,
      imageUrl: null,
      category: 'Demo',
      isPopular: true,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_03',
      shopId: 'demo_shop_01',
      barberId: null,
      nameEn: 'Beard Trim',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 4.0,
      durationMinutes: 30,
      imageUrl: null,
      category: 'Demo',
      isPopular: false,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_04',
      shopId: 'demo_shop_02',
      barberId: null,
      nameEn: 'Fade + Line Up',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 7.0,
      durationMinutes: 45,
      imageUrl: null,
      category: 'Demo',
      isPopular: true,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_05',
      shopId: 'demo_shop_02',
      barberId: null,
      nameEn: 'Haircut + Beard',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 10.0,
      durationMinutes: 60,
      imageUrl: null,
      category: 'Demo',
      isPopular: false,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_06',
      shopId: 'demo_shop_03',
      barberId: null,
      nameEn: 'Classic Haircut',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 6.0,
      durationMinutes: 45,
      imageUrl: null,
      category: 'Demo',
      isPopular: false,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_07',
      shopId: 'demo_shop_03',
      barberId: null,
      nameEn: 'Beard Sculpt',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 5.0,
      durationMinutes: 35,
      imageUrl: null,
      category: 'Demo',
      isPopular: false,
      isActive: true,
      createdAt: DateTime.now(),
    ),
    Service(
      id: 'demo_service_08',
      shopId: 'demo_shop_04',
      barberId: null,
      nameEn: 'Studio Fade',
      nameAr: '',
      descriptionEn: '',
      descriptionAr: '',
      priceBhd: 7.0,
      durationMinutes: 45,
      imageUrl: null,
      category: 'Demo',
      isPopular: true,
      isActive: true,
      createdAt: DateTime.now(),
    ),
  ];

  static final reels = <Reel>[
    Reel(
      id: 'demo_post_01',
      barberId: 'demo_barber_01',
      shopId: 'demo_shop_01',
      mediaType: 'image',
      mediaUrl: HallaqImages.haircutSkinFade(variant: '01'),
      imageUrl: HallaqImages.haircutSkinFade(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.haircutSkinFade(variant: '01'),
      caption: 'Skin fade with clean line up.',
      viewsCount: 0,
      likesCount: 536,
      commentsCount: 24,
      savesCount: 61,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 20)),
    ),
    Reel(
      id: 'demo_post_02',
      barberId: 'demo_barber_04',
      shopId: 'demo_shop_02',
      mediaType: 'image',
      mediaUrl: HallaqImages.haircutTaperFade(variant: '01'),
      imageUrl: HallaqImages.haircutTaperFade(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.haircutTaperFade(variant: '01'),
      caption: 'Clean taper fade with premium finish.',
      viewsCount: 0,
      likesCount: 812,
      commentsCount: 31,
      savesCount: 104,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(hours: 6, minutes: 10)),
    ),
    Reel(
      id: 'demo_post_03',
      barberId: 'demo_barber_07',
      shopId: 'demo_shop_03',
      mediaType: 'image',
      mediaUrl: HallaqImages.haircutTexturedCrop(variant: '01'),
      imageUrl: HallaqImages.haircutTexturedCrop(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.haircutTexturedCrop(variant: '01'),
      caption: 'Textured crop with clean fade.',
      viewsCount: 0,
      likesCount: 391,
      commentsCount: 18,
      savesCount: 47,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(hours: 11, minutes: 35)),
    ),
    Reel(
      id: 'demo_post_04',
      barberId: 'demo_barber_10',
      shopId: 'demo_shop_04',
      mediaType: 'image',
      mediaUrl: HallaqImages.italianBeard(variant: '01'),
      imageUrl: HallaqImages.italianBeard(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.italianBeard(variant: '01'),
      caption: 'Italian beard styling with sharp lines.',
      viewsCount: 0,
      likesCount: 224,
      commentsCount: 9,
      savesCount: 33,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
    ),
    Reel(
      id: 'demo_post_05',
      barberId: null,
      shopId: 'demo_shop_02',
      mediaType: 'image',
      mediaUrl: HallaqImages.luxuryBarberInterior(variant: '02'),
      imageUrl: HallaqImages.luxuryBarberInterior(variant: '02'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.luxuryBarberInterior(variant: '02'),
      caption: 'Seef Cuts Lounge interior. Premium chairs, dark mood, gold accents.',
      viewsCount: 0,
      likesCount: 1042,
      commentsCount: 48,
      savesCount: 201,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
    ),
    Reel(
      id: 'demo_post_06',
      barberId: 'demo_barber_02',
      shopId: 'demo_shop_01',
      mediaType: 'image',
      mediaUrl: HallaqImages.haircutLowFade(variant: '01'),
      imageUrl: HallaqImages.haircutLowFade(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.haircutLowFade(variant: '01'),
      caption: 'Low fade with modern texture.',
      viewsCount: 0,
      likesCount: 650,
      commentsCount: 27,
      savesCount: 88,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(hours: 4, minutes: 45)),
    ),
    Reel(
      id: 'demo_post_07',
      barberId: null,
      shopId: 'demo_shop_01',
      mediaType: 'image',
      mediaUrl: HallaqImages.luxuryBarberInterior(variant: '01'),
      imageUrl: HallaqImages.luxuryBarberInterior(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.luxuryBarberInterior(variant: '01'),
      caption: 'Manama Barbershop. Premium grooming station ready.',
      viewsCount: 0,
      likesCount: 832,
      commentsCount: 22,
      savesCount: 96,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 2)),
    ),
    Reel(
      id: 'demo_post_08',
      barberId: null,
      shopId: 'demo_shop_04',
      mediaType: 'image',
      mediaUrl: HallaqImages.barberShopExterior(variant: '01'),
      imageUrl: HallaqImages.barberShopExterior(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.barberShopExterior(variant: '01'),
      caption: 'Juffair Fade Studio. Premium storefront and vibe.',
      viewsCount: 0,
      likesCount: 520,
      commentsCount: 18,
      savesCount: 74,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 7)),
    ),
    Reel(
      id: 'demo_post_09',
      barberId: null,
      shopId: 'demo_shop_03',
      mediaType: 'image',
      mediaUrl: HallaqImages.haircutBeforeAfter(variant: '01'),
      imageUrl: HallaqImages.haircutBeforeAfter(variant: '01'),
      videoUrl: null,
      thumbnailUrl: HallaqImages.haircutBeforeAfter(variant: '01'),
      caption: 'Before/after transformation. Clean fade and beard line.',
      viewsCount: 0,
      likesCount: 701,
      commentsCount: 14,
      savesCount: 92,
      sharesCount: 0,
      createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 4)),
    ),
  ];

  static final reviews = <Review>[
    Review(
      id: 'demo_review_01',
      customerId: 'demo_customer_01',
      barberId: 'demo_barber_01',
      shopId: null,
      rating: 5,
      comment: 'Perfect fade and clean beard line. Premium service from start to finish.',
      imageUrl: null,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Review(
      id: 'demo_review_02',
      customerId: 'demo_customer_02',
      barberId: null,
      shopId: 'demo_shop_02',
      rating: 5,
      comment: 'Luxury lounge vibe with consistent results. Highly recommended.',
      imageUrl: null,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
    ),
    Review(
      id: 'demo_review_03',
      customerId: 'demo_customer_03',
      barberId: 'demo_barber_10',
      shopId: null,
      rating: 5,
      comment: 'Sharp fade and premium beard sculpt. Clean, consistent, and fast.',
      imageUrl: null,
      createdAt: DateTime.now().subtract(const Duration(days: 9)),
    ),
  ];

  static final bookingsUpcoming = <Booking>[
    Booking(
      id: 'demo_booking_up_01',
      customerProfileId: 'demo_customer_01',
      barberId: 'demo_barber_04',
      shopId: 'demo_shop_02',
      serviceId: 'demo_service_04',
      startAt: DateTime.now().add(const Duration(days: 1, hours: 3)),
      endAt: DateTime.now().add(const Duration(days: 1, hours: 3, minutes: 45)),
      status: BookingStatus.confirmed,
    ),
    Booking(
      id: 'demo_booking_up_02',
      customerProfileId: 'demo_customer_01',
      barberId: 'demo_barber_10',
      shopId: 'demo_shop_04',
      serviceId: 'demo_service_08',
      startAt: DateTime.now().add(const Duration(days: 2, hours: 6)),
      endAt: DateTime.now().add(const Duration(days: 2, hours: 6, minutes: 45)),
      status: BookingStatus.pending,
    ),
  ];

  static final bookingsPast = <Booking>[
    Booking(
      id: 'demo_booking_past_01',
      customerProfileId: 'demo_customer_01',
      barberId: 'demo_barber_01',
      shopId: 'demo_shop_01',
      serviceId: 'demo_service_02',
      startAt: DateTime.now().subtract(const Duration(days: 8, hours: 2)),
      endAt: DateTime.now().subtract(const Duration(days: 8, hours: 1, minutes: 0)),
      status: BookingStatus.completed,
    ),
    Booking(
      id: 'demo_booking_past_02',
      customerProfileId: 'demo_customer_01',
      barberId: 'demo_barber_10',
      shopId: 'demo_shop_04',
      serviceId: 'demo_service_08',
      startAt: DateTime.now().subtract(const Duration(days: 16, hours: 5)),
      endAt: DateTime.now().subtract(const Duration(days: 16, hours: 3, minutes: 50)),
      status: BookingStatus.completed,
    ),
  ];

  static Barbershop? shopById(String id) {
    for (final s in _shopsAll) {
      if (s.id == id) return s;
    }
    return null;
  }

  static Barber? barberById(String id) {
    for (final b in _barbersAll) {
      if (b.id == id) return b;
    }
    return null;
  }

  static Barber? barberByRef(String ref) {
    for (final b in _barbersAll) {
      if (b.id == ref || b.slug == ref) return b;
    }
    return null;
  }

  static List<Barber> barbersForShop(String shopId) {
    return _barbersAll.where((b) => b.shopId == shopId).toList(growable: false);
  }

  static List<Reel> reelsForBarber(String barberId, {int limit = 18}) {
    return reels.where((r) => r.barberId == barberId).take(limit).toList(growable: false);
  }

  static List<Reel> reelsForShop(String shopId, {int limit = 18}) {
    return reels.where((r) => r.shopId == shopId).take(limit).toList(growable: false);
  }
}
