$ErrorActionPreference = "Stop"

Write-Output ""
Write-Output "HALLAQ Production Setup (Dry Run)"
Write-Output ""

Write-Output "GoDaddy DNS"
Write-Output "  A     @         76.76.21.21"
Write-Output "  CNAME app       cname.vercel-dns.com"
Write-Output "  CNAME business  cname.vercel-dns.com"
Write-Output "  CNAME admin     cname.vercel-dns.com"
Write-Output "  CNAME www       cname.vercel-dns.com (optional, then redirect www -> apex in Vercel)"
Write-Output ""

Write-Output "Vercel Projects (4)"
Write-Output "  Landing   rootDir=apps/landing   domain=hallaq.com"
Write-Output "  Customer  rootDir=apps/customer  domain=app.hallaq.com"
Write-Output "  Business  rootDir=apps/shop      domain=business.hallaq.com"
Write-Output "  Admin     rootDir=apps/admin     domain=admin.hallaq.com"
Write-Output ""

Write-Output "Vercel Production Env Vars (set in EACH web project)"
Write-Output "  NEXT_PUBLIC_SUPABASE_URL"
Write-Output "  NEXT_PUBLIC_SUPABASE_ANON_KEY"
Write-Output "  NEXT_PUBLIC_HALLAQ_ROUTING_MODE=subdomain"
Write-Output "  NEXT_PUBLIC_LANDING_URL=https://hallaq.com"
Write-Output "  NEXT_PUBLIC_APP_URL=https://app.hallaq.com"
Write-Output "  NEXT_PUBLIC_BUSINESS_URL=https://business.hallaq.com"
Write-Output "  NEXT_PUBLIC_ADMIN_URL=https://admin.hallaq.com"
Write-Output "  NEXT_PUBLIC_API_URL=https://api.hallaq.com"
Write-Output ""

Write-Output "Admin-only env vars (admin project)"
Write-Output "  SUPABASE_SERVICE_ROLE_KEY"
Write-Output "  FFMPEG_PATH (optional)"
Write-Output ""

Write-Output "Supabase Auth (Dashboard)"
Write-Output "  Site URL: https://app.hallaq.com"
Write-Output "  Redirect URLs:"
Write-Output "    https://hallaq.com/auth/callback"
Write-Output "    https://app.hallaq.com/auth/callback"
Write-Output "    https://business.hallaq.com/auth/callback"
Write-Output "    https://admin.hallaq.com/auth/callback"
Write-Output ""

Write-Output "Supabase Migrations to Apply in Production"
Write-Output "  supabase/migrations/20260611170000_role_sync_and_shop_claim_hardening.sql"
Write-Output "  supabase/migrations/20260611174000_barbers_shop_assignment_guard.sql"
Write-Output ""

Write-Output "Docs"
Write-Output "  docs/production/architecture.md"
Write-Output "  docs/production/environment.md"
Write-Output "  docs/production/deployment-checklist.md"
Write-Output "  docs/production/readiness-report.md"
Write-Output ""

